### ISSUE TITLE
Разработка классификатора знаков

### ISSUE THREAD

**Issue by KaiL4eK** [lsd-maddrive/adas_system#4]
Необходимо разработать классификатор знаков по требуемым для Robocross.
План разработки следующий:
- Ознакомление с подходами разработки
- Обучение классификатора на датасете RTSD
- Комментирование кода и приведение ноутбука в порядок
- Оценка показателей классификации
> Следующие дополнения также требуют переоценки
- Анализ ошибок классификатора
- Дополнение обучения классификации аугментациями https://albumentations.ai/
- Дополнение вывода метрик при обучении в Tensorboard train: loss, valid: calssification metrics (по каждому классу и усредненные по macro), loss, а также lr
- Добавление классов в датасет

**Comment by KaiL4eK** [comment]
В issue #1 заливаем, что есть а потом в новой ветке работаем по этой задаче

**Comment by GeneralFire** [comment]
Готово:

- Ознакомление с подходами разработки
- Обучение классификатора на датасете RTSD
- Комментирование кода и приведение ноутбука в порядок

Перешел на #9

**Comment by GeneralFire** [comment]
Готово:
* Метрики
* Аугментация
